# Generated by Django 6.0.1 on 2026-02-02 10:57

import django.contrib.auth.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='total_xp',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Phone number of the user', max_length=128, region=None, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
