# Generated by Django 6.0.1 on 2026-02-02 11:02

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_usermodel_rank_remove_usermodel_total_xp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Phone number of the user', max_length=128, region=None, unique=True, verbose_name='Phone Number'),
        ),
    ]
