# Generated by Django 6.0.1 on 2026-02-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usermodel_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='phone_number_verified',
            field=models.BooleanField(default=False, help_text='Phone number of the user', verbose_name='Phone Number Verified'),
        ),
    ]
