# Generated by Django 6.0.1 on 2026-02-03 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usermodel_phone_number_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='gender',
        ),
    ]
