# Generated by Django 6.0.1 on 2026-02-03 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_usermodel_gender'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='username',
        ),
    ]
