# Generated by Django 6.0.1 on 2026-02-07 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for the feature",
                        max_length=100,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the feature",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for the plan",
                        max_length=50,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the plan",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the plan",
                        verbose_name="Description",
                    ),
                ),
                (
                    "trial_months",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Number of trial months for the plan",
                        verbose_name="Trial Months",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        help_text="Price amount", verbose_name="Amount"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="BDT",
                        help_text="Currency code",
                        max_length=10,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "duration_months",
                    models.PositiveSmallIntegerField(
                        help_text="Duration of the subscription in months",
                        verbose_name="Duration Months",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this price is currently active",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        help_text="Plan associated with this price",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="billing.plan",
                        verbose_name="Plan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trial_ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the trial period ends",
                        null=True,
                        verbose_name="Trial Ends At",
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the subscription ends",
                        null=True,
                        verbose_name="Ends At",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                        ],
                        help_text="Current status of the subscription",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "auto_renew",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the subscription should auto-renew",
                        verbose_name="Auto Renew",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the subscription was created",
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the subscription was last modified",
                        verbose_name="Modified",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        help_text="Subscription plan",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="billing.plan",
                        verbose_name="Plan",
                    ),
                ),
                (
                    "price",
                    models.ForeignKey(
                        help_text="Price for this subscription",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="billing.price",
                        verbose_name="Price",
                    ),
                ),
                (
                    "teacher",
                    models.OneToOneField(
                        help_text="Teacher who owns this subscription",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="teachers.teacher",
                        verbose_name="Teacher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeatureUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "used",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times the feature has been used",
                        verbose_name="Used",
                    ),
                ),
                (
                    "last_reset_at",
                    models.DateTimeField(
                        help_text="Last time the usage counter was reset",
                        verbose_name="Last Reset At",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        help_text="Feature being tracked",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="billing.feature",
                        verbose_name="Feature",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        help_text="Teacher using the feature",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teachers.teacher",
                        verbose_name="Teacher",
                    ),
                ),
            ],
            options={
                "unique_together": {("teacher", "feature")},
            },
        ),
        migrations.CreateModel(
            name="PlanFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monthly_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Monthly usage limit for this feature",
                        null=True,
                        verbose_name="Monthly Limit",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        help_text="Feature included in the plan",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="billing.feature",
                        verbose_name="Feature",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        help_text="Plan associated with this feature",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="billing.plan",
                        verbose_name="Plan",
                    ),
                ),
            ],
            options={
                "unique_together": {("plan", "feature")},
            },
        ),
    ]
