# Generated by Django 6.0.1 on 2026-02-06 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the teacher', max_length=255, verbose_name='Name')),
                ('avatar', models.ImageField(blank=True, help_text='Avatar (or profile pic) of the teacher', upload_to='uploads/avatars/', verbose_name='Avatar')),
                ('fee_day', models.PositiveSmallIntegerField(help_text='Day of the month to take the fee', verbose_name='Fee Day')),
                ('sms_tokens_count', models.PositiveSmallIntegerField(default=0, help_text='Number of SMS tokens the teacher has', verbose_name='SMS Tokens Count')),
                ('free_sms_tokens_count', models.PositiveSmallIntegerField(default=0, help_text='Number of Free SMS tokens the teacher has', verbose_name='Free SMS Tokens Count')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
