"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from corsheaders.defaults import (
    default_headers,
)
from environ import Env
from command_scheduler.enums import ScheduleType
from command_scheduler.utils import args


SITE_ID = 1

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

SILENCED_SYSTEM_CHECKS = ["rest_framework.W001"]

ENV_FILE = ".env"
Env.read_env(BASE_DIR / ENV_FILE)
env = Env()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1"]
INTERNAL_IPS = ["127.0.0.1"]


# Application definition
DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

THIRD_PARTY_APPS = [
    "corsheaders",
    "notifications",
    "django_filters",
    "django_extensions",
    "phonenumber_field",
    "rest_framework",
    "rest_framework.authtoken",
    "drf_spectacular",
    "allauth",
    "allauth.account",
    "allauth.headless",
]

LOCAL_APPS = [
    "command_scheduler",
    "tutor_khata.common",
    "tutor_khata.docs",
    "tutor_khata.accounts",
    "tutor_khata.users",
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

ROOT_URLCONF = "config.urls"


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Mail
DEFAULT_FROM_EMAIL = "tutor_khata.noreply@gmail.com"

# User Model
AUTH_USER_MODEL = "users.UserModel"

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static"


# Log
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        #         "db_query": {
        #             "level": "DEBUG",
        #             "class": "logging.FileHandler",
        #             "filename": "tmp/logs/db_queries.log",
        #         },
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS
CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_HEADERS = (
    *default_headers,
    "X-Session-Token",
    "location",
)

# Rest Framework
REST_FRAMEWORK = {
    # API Versioning
    "DEFAULT_VERSION": "v1",
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.AcceptHeaderVersioning",

    # Pagination
    "PAGE_SIZE": 15,
    # Test
    "TEST_REQUEST_DEFAULT_FORMAT": "json",
}

# Api Docs
SPECTACULAR_SETTINGS = {
    "TITLE": "Tutor Khata",
    "DESCRIPTION": "The api documentation of Tutor Khata API",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "EXTERNAL_DOCS": {
        "url": "https://allauth.org/docs/draft-api",
        "description": "Authentication",
    },
    "SCHEMA_PATH_PREFIX": r"/api/",
}

# All-Auth
ACCOUNT_AUTHENTICATION_METHOD = "username_email"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "optional"
ACCOUNT_CHANGE_EMAIL = True
ACCOUNT_EMAIL_NOTIFICATIONS = True
ACCOUNT_USERNAME_MIN_LENGTH = 3
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = False
# MFA_TOTP_ISSUER = "Tutor Khata"

# All-Auth : Headless
HEADLESS_JWT_PRIVATE_KEY = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDcQzTiiPurrlbJ
coP8crbl0HLBvZFpbo2X0N+qQfa6HXWmoybl1DreHaqaXuo4tU+7nQ0jel2Lr/3K
N/vcD/D8SAFyBDL9OZyDVUtIjML45kozPopKEC3j2T12oGhN33IOsB/H6EZF04it
aLSP0ZYhMfpxzuHZosrkHD1mdq8daFDkr+Ht3+Zw5nEPJepOESOa6OqW7YPk3EG1
Qgc8H7xPWDHXen890ZQbNVjlNkeu03rXcf2AAgQzK2XBmJbpzzoTJFPEG6COrRjC
WUFmQ02WHQuKRULMklX3tGuU0GdF69NERL1UBjg+Wdrgnu6gBKx3r6+nmFP5/pvb
U8L5FINzAgMBAAECggEAS+JBjYw4/HBPSQ7RZv9UgL98UcAQIV0rnfKhpAQezwcI
OfU6mPKxp0VcOdvaYNgiVJYqaR8mrFHhIzJ/bFT3psrd6JyGvpQDFoIjsiaAo4Sf
aqEwvoxtavK0iLKBzNZe8q19/X7J+xOCIpAQqP3BdcVErcHjMHoz4TvTcYIRGZVr
rgVvNeTbDVCAjT/GLY9zOQGdH0lJB2IuPdm/tZWsC+HzgRHvGnH4HqrtaAYfKHbN
3kEr9mGCxuJaJXPoPpbfrfTH/+1pEv2dqVd1yvK/kBiVhlf5lGzU9bobyG54gmLH
vNicNzIMuNEsiErGuK/fUPbdrC4DA107LQSDjH5xBQKBgQDunuyqpW3aKTiuuAkD
5mez0StfPEr+/1c//xmZKEqB+TavfZLMgHQ0ocYwEf/Q+UpsCNyz5XaVBX0UR8BG
I9aUAht7Uwq07qWjr72UTGiIm7Xh319rXC5LDQbj0c9lSCFcWy53oQylFbVK7GBv
CYCszBjihYtuJY13+SS6DEChPwKBgQDsTf4pJWvF2zvVj7cbNu3B8IqpokbERQZR
UpAoMjzaIBfMncVLy7N69lo+yxx8XDmCwyR2zv7d7m3gjKvmxyv6vJOb2QzILWLg
Kxd0OU5rTlDDQvdNpB9XCnVGj5OZrPrn1+lMa1HsVdrrYVTRSTGNhNgkVD4afGdQ
rZJ+M6+czQKBgE/gXzTYX6dxuQmzjUEC9Z/Z2vzsP+aQLvK7QCRmulo7xDSGgod2
UG/131PkEpAvgtwbM1X87+7+gVoykohoIsI02mIz8BeU81mR0JI96ZghF4desKBN
oSl6WN4WM6ihtpkl5K4i+Qqh86f67GT+91XglEvvjDb41xxcCBFHXLMdAoGBAOUG
WlVKvX+QEhfUKGWqARm8psfuTaQgOhVLbghnWG8YN7jLGNNzZErCxYiilsM5J0xD
Ee5MhNxYIApIjLspQsjLSEz+OtMwmeomGZ89g3Gg/8mf98w6S12y9yMiOK3y52MY
8jZstYPXWkxTkz8cL3i3zjy3oVFOTVv2PksukP/pAoGBAM81Ae6NGqTcf15p68ji
MHZBRibuociye8ULwgfDHein7LMDYJJ69iIYzrCniLn7+MAkquFEa9RfyoPsKhpR
O03Ga7sreZl83lT82BEao08PyP6/ejXeJIk8jHJjTbwlXYv/rqelhUr9Ow9JBO7I
aOGsJgUN1ALULbsKE/aucOFt
-----END PRIVATE KEY-----
"""
FRONTEND_BASE_URL = "https://tutor_khata.com"
HEADLESS_ONLY = True
HEADLESS_TOKEN_STRATEGY = "tutor_khata.authentication.tokens.SessionTokenStrategy"
HEADLESS_FRONTEND_URLS = {
    "account_confirm_email": FRONTEND_BASE_URL + "/account/verify-email/{key}",
    "account_reset_password_from_key": FRONTEND_BASE_URL
    + "/account/password/reset/{key}",
}


# Tutor Khata
# tutor_khata.docs
SCHEMA_DIR = STATIC_ROOT / "docs"

# tutor_khata.users
USERNAME_MAX_LENGTH = 35
USERNAME_MAX_SUGGESTIONS = 3
USERNAME_GENERATION_MAX_ATTEMPTS = 10
